'use strict';
(()=>{
const $=id=>document.getElementById(id),post=s=>window.chrome?.webview?.postMessage(s),main=$('island'),handle=$('handle'),details=$('details');
let config=null,glassReceive=null,mode='bar',raf=0,last=0,drag=null,paused=false,painted=false,widgets=null,clockTimer=0,fluid=0,flow=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),s={w:{x:500,v:0,target:500},h:{x:42,v:0,target:42}},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function step(p,dt){const omega=11,y=p.x-p.target,j=p.v+omega*y,e=Math.exp(-omega*dt);p.x=p.target+(y+j*dt)*e;p.v=(p.v-omega*j*dt)*e;if(Math.abs(p.x-p.target)<.15&&Math.abs(p.v)<.4){p.x=p.target;p.v=0;}}
function dims(){const q=config?.scale||1;return{q,bar:Math.max(280,innerWidth-8),pill:Math.min(innerWidth-8,272*q),wide:Math.min(innerWidth-8,540*q),low:48*q,high:300*q};}
function targets(){const d=dims();s.w.target=mode==='bar'?d.bar:mode==='open'?d.wide:d.pill;s.h.target=mode==='bar'?42*d.q:mode==='open'?d.high:d.low;}
function change(next){mode=next;main.dataset.mode=mode;targets();details.inert=mode!=='open';handle.setAttribute('aria-expanded',String(mode==='open'));handle.setAttribute('aria-label',mode==='bar'?'点击收拢为灵动岛':'点击恢复整栏，或按住向下拖动展开');wake();post('mode:'+mode);}
function draw(){if(!config)return;const d=dims(),w=clamp(s.w.x,80,innerWidth-6),h=clamp(s.h.x,30,innerHeight-6),x=(innerWidth-w)/2,y=12;
main.style.cssText=`left:${x}px;top:${y}px;width:${w}px;height:${h}px;--s:${d.q};border-radius:${Math.min(h/2,30*d.q)}px`;
const bar=clamp((w-d.wide)/(Math.max(1,d.bar-d.wide)),0,1),content=clamp((h-d.low)/(d.high-d.low),0,1);
$('bar-left').style.opacity=bar;$('bar-right').style.opacity=bar;for(const id of ['bar-left','bar-right']){$(id).inert=mode!=='bar';$(id).style.pointerEvents=mode==='bar'?'auto':'none';}
handle.style.width=mode==='bar'?Math.max(100,w-(innerWidth<850?430:720)*d.q)+'px':'100%';handle.style.height=(mode==='bar'?42*d.q:d.low)+'px';$('island-orb').style.opacity=1-bar;$('island-summary').style.opacity=1-bar;$('grip').style.opacity=(1-bar)*.25;
details.style.opacity=clamp((content-.62)/.38,0,1);details.style.pointerEvents=mode==='open'&&content>.98?'auto':'none';details.style.transform=`translateY(${(1-content)*-8*d.q}px)`;
const moving=!!drag||Object.values(s).some(p=>Math.abs(p.x-p.target)>.2||Math.abs(p.v)>.4),card={name:'TopIsland',x,y,w,h,r:Math.min(h/2,30*d.q),rimStrength:.45,fixedShape:mode==='bar'||moving,motionFluid:reduced.matches?0:fluid,flowY:flow};glassReceive?.({type:'geometry',externallyDriven:true,cards:[card]});
window.islandState={mode,width:w,height:h,velocityWidth:s.w.v,velocityHeight:s.h.v,dragging:!!drag,paused,ready:painted,motionFluid:card.motionFluid,flowY:flow};if(window.islandTrace)window.islandTrace.push({time:performance.now(),...window.islandState});}
function frame(now){raf=0;const dt=Math.max(.001,Math.min(.034,(now-last)/1000||.016));last=now;if(!drag){for(const p of Object.values(s)){if(reduced.matches){p.x=p.target;p.v=0;}else step(p,dt);}}else if(now-drag.time>64){s.w.v=0;s.h.v=0;}const d=dims(),vx=-s.w.v/Math.max(1,d.bar-d.pill),vy=s.h.v/Math.max(1,d.high-d.low),rate=Math.max(Math.abs(vx),Math.abs(vy)),direction=Math.abs(vy)>Math.abs(vx)?Math.sign(vy):Math.sign(vx),target=reduced.matches?0:clamp(rate/4,0,1);fluid+=(target-fluid)*(1-Math.exp(-14*dt));flow+=(direction-flow)*(1-Math.exp(-12*dt));if(target===0&&fluid<.002)fluid=0;draw();if((!drag&&Object.values(s).some(p=>p.x!==p.target||p.v!==0))||Math.abs(fluid-target)>.002)raf=requestAnimationFrame(frame);}
function wake(){if(!raf){last=performance.now();raf=requestAnimationFrame(frame);}}
PrismGlassRenderer($('glass'),message=>{if(message==='painted'){painted=true;document.body.dataset.ready='true';post('painted');}else if(message.startsWith('error:'))post(message);else if(message.startsWith('widget-shapes:')){window.islandOutline=JSON.parse(message.substring(14));post('outline:'+message.substring(14));}},fn=>glassReceive=fn);
function cancelDrag(){if(!drag)return;const was=drag;drag=null;try{handle.releasePointerCapture(was.id);}catch{}post('drag:false');change(s.h.x>dims().low+50*dims().q?'open':'pill');}
handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,start:e.clientY,y:e.clientY,time:performance.now(),startH:s.h.x,startW:s.w.x,was:mode,moved:false,vy:0};handle.setPointerCapture(e.pointerId);post('drag:true');});
handle.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const now=performance.now(),delta=e.clientY-drag.start,d=dims();if(Math.abs(delta)>5*d.q)drag.moved=true;if(drag.was==='bar')return;const next=clamp(drag.startH+delta,d.low,d.high+10*d.q),dt=Math.max(.008,(now-drag.time)/1000);drag.vy=drag.vy*.5+clamp((next-s.h.x)/dt,-1800*d.q,1800*d.q)*.5;s.h.x=next;s.h.v=drag.vy;const progress=clamp((next-d.low)/(d.high-d.low),0,1);s.w.x=d.pill+(d.wide-d.pill)*progress;s.w.v=drag.vy*(d.wide-d.pill)/(d.high-d.low);drag.y=e.clientY;drag.time=now;details.inert=true;wake();});
handle.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;const done=drag;drag=null;if(performance.now()-done.time>64){s.w.v=0;s.h.v=0;}try{handle.releasePointerCapture(e.pointerId);}catch{}post('drag:false');if(!done.moved){change(done.was==='bar'?'pill':'bar');return;}if(done.was==='bar'){change('pill');return;}const d=dims();change(s.h.x+s.h.v*.12>d.low+(d.high-d.low)*.35?'open':'pill');});
handle.addEventListener('pointercancel',cancelDrag);handle.addEventListener('lostpointercapture',()=>{if(drag)cancelDrag();});
handle.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();change('open');}else if(e.key==='Enter'||e.key===' '){e.preventDefault();change(mode==='bar'?'pill':'bar');}});
$('collapse').addEventListener('click',()=>change('pill'));document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelDrag();change('pill');}});
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>post('action:'+button.dataset.action)));
for(const event of ['pointermove','pointerdown','pointerup'])document.addEventListener(event,e=>glassReceive?.({type:'pointer',x:e.clientX,y:e.clientY,down:e.buttons!==0}));document.addEventListener('pointerleave',()=>{if(!drag)glassReceive?.({type:'pointer',x:-999,y:-999,down:false});});
function clock(){const now=new Date();$('date').textContent=now.toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit',weekday:'short'})+' '+now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});const focus=widgets?.focus,music=widgets?.music;if(focus){let seconds=focus.deadline>0?Math.max(0,focus.deadline-Math.floor(Date.now()/1000)):focus.remaining;seconds=Math.max(0,Number(seconds)||0);const time=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('focus-time').textContent=time;$('focus-state').textContent=!focus.available?'专注组件尚未就绪':focus.deadline>0?'专注进行中':'准备开始';$('focus-toggle').textContent=focus.deadline>0?'暂停':'开始';document.querySelectorAll('[data-action^="focus-"]').forEach(el=>el.disabled=!focus.available);$('island-summary').textContent=focus.deadline>0?'专注 '+time:music?.playing?music.title:'工作台';}}
function receive(m){if(m.type==='layout'){config=m;paused=!!m.paused;document.body.classList.toggle('astro',m.theme==='Astro');targets();glassReceive?.({type:'layout',width:innerWidth,height:innerHeight,sceneWidth:m.width,sceneHeight:m.height,originX:m.x,originY:m.y,cards:[],theme:m.theme,paused:paused||reduced.matches});glassReceive?.({type:'wallpaper',version:m.wallpaper});if(!window.islandState){s.w.x=s.w.target;s.h.x=s.h.target;}wake();}else if(m.type==='widgets'){widgets=m;$('music-title').textContent=m.music?.title||'等待播放';$('music-artist').textContent=m.music?.artist||'开始播放后显示歌曲';$('media-toggle').textContent=m.music?.playing?'Ⅱ':'▶';clock();}else if(m.type==='status'){$('disk').textContent=m.disk||'C 盘';}else if(m.type==='feedback')$('feedback').textContent=m.message||'';else if(m.type==='dismiss'&&mode==='open'&&!drag)change('pill');}
window.chrome?.webview?.addEventListener('message',e=>receive(e.data));window.addEventListener('resize',()=>{targets();wake();});window.addEventListener('blur',cancelDrag);clock();clockTimer=setInterval(clock,1000);window.addEventListener('pagehide',()=>{clearInterval(clockTimer);cancelAnimationFrame(raf);});window.PrismIsland={receive,change,step};post('ready');
})();
