using System;using System.Collections.Generic;using System.Diagnostics;using System.Globalization;using System.IO;using System.Runtime.InteropServices;using System.Threading;using System.Threading.Tasks;using System.Web.Script.Serialization;
internal sealed class QuotaWindow {public double remainingPercent;public int windowDurationMins;public long resetsAt;}
internal sealed class QuotaSnapshot {public long fetchedAt;public QuotaWindow weekly,shortTerm;public string state="unknown",message="尚未读取额度";}
// Only the official account/rateLimits/read request is sent. Authentication stays inside Codex CLI.
internal sealed class QuotaReader : IDisposable {
 readonly object gate=new object();readonly string cache;readonly JavaScriptSerializer json=new JavaScriptSerializer();Process running;IntPtr job;bool disposed;
 [StructLayout(LayoutKind.Sequential)]struct BASIC_LIMIT{public long processTime,jobTime;public uint flags;public UIntPtr minimum,maximum;public uint active;public UIntPtr affinity;public uint priority,scheduling;}
 [StructLayout(LayoutKind.Sequential)]struct IO_COUNTERS{public ulong readOps,writeOps,otherOps,readBytes,writeBytes,otherBytes;}
 [StructLayout(LayoutKind.Sequential)]struct EXTENDED_LIMIT{public BASIC_LIMIT basic;public IO_COUNTERS io;public UIntPtr processMemory,jobMemory,peakProcess,peakJob;}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)]static extern IntPtr CreateJobObject(IntPtr attributes,string name);
 [DllImport("kernel32.dll")]static extern bool SetInformationJobObject(IntPtr job,int type,ref EXTENDED_LIMIT value,uint size);
 [DllImport("kernel32.dll")]static extern bool AssignProcessToJobObject(IntPtr job,IntPtr process);
 [DllImport("kernel32.dll")]static extern bool CloseHandle(IntPtr handle);
 public QuotaReader(string root){cache=Path.Combine(root,"quota-cache.json");}
 public static long Now(){return (long)(DateTime.UtcNow-new DateTime(1970,1,1,0,0,0,DateTimeKind.Utc)).TotalSeconds;}
 public static bool Fresh(QuotaSnapshot snapshot,long now){return snapshot!=null&&snapshot.fetchedAt>0&&now>=snapshot.fetchedAt-30&&now-snapshot.fetchedAt<=600;}
 static bool Number(object value,out double result){result=0;if(!(value is int||value is long||value is double||value is decimal))return false;result=Convert.ToDouble(value,CultureInfo.InvariantCulture);return !Double.IsNaN(result)&&!Double.IsInfinity(result);}
 static Dictionary<string,object> Map(object value){return value as Dictionary<string,object>;}
 static object Value(Dictionary<string,object> map,string key){object result;return map!=null&&map.TryGetValue(key,out result)?result:null;}
 static QuotaWindow Window(object value){var map=Map(value);double used,minutes,reset;if(!Number(Value(map,"usedPercent"),out used)||!Number(Value(map,"windowDurationMins"),out minutes)||minutes<=0||minutes>525600)return null;bool hasReset=Number(Value(map,"resetsAt"),out reset);return new QuotaWindow{remainingPercent=Math.Max(0,Math.Min(100,100-used)),windowDurationMins=(int)minutes,resetsAt=hasReset&&reset>0?(long)reset:0};}
 public static QuotaSnapshot Parse(string text,long fetchedAt){var serializer=new JavaScriptSerializer();var root=Map(serializer.DeserializeObject(text));var result=Map(Value(root,"result"))??root;var buckets=Map(Value(result,"rateLimitsByLimitId"));var bucket=Map(Value(buckets,"codex"))??Map(Value(result,"rateLimits"));var snapshot=new QuotaSnapshot{fetchedAt=fetchedAt,state="fresh",message="已从 Codex 读取"};foreach(var key in new[]{"primary","secondary"}){var window=Window(Value(bucket,key));if(window==null)continue;if(window.windowDurationMins==10080)snapshot.weekly=window;else if(window.windowDurationMins<10080&&(snapshot.shortTerm==null||window.windowDurationMins>snapshot.shortTerm.windowDurationMins))snapshot.shortTerm=window;}if(snapshot.weekly==null&&snapshot.shortTerm==null){snapshot.state="unknown";snapshot.message="当前账户未提供可用额度窗口";}return snapshot;}
 static bool ValidCached(QuotaWindow window){return window==null||(!Double.IsNaN(window.remainingPercent)&&!Double.IsInfinity(window.remainingPercent)&&window.remainingPercent>=0&&window.remainingPercent<=100&&window.windowDurationMins>0&&window.windowDurationMins<=10080&&window.resetsAt>=0);}
 public QuotaSnapshot Cached(){try{if(File.Exists(cache)&&new FileInfo(cache).Length<4096){var snapshot=json.Deserialize<QuotaSnapshot>(File.ReadAllText(cache));if(snapshot!=null&&snapshot.fetchedAt>0&&ValidCached(snapshot.weekly)&&ValidCached(snapshot.shortTerm)){snapshot.state="stale";snapshot.message="上次额度记录，等待刷新";return snapshot;}}}catch{}return new QuotaSnapshot();}
 static string Cli(){var basePath=Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);var exe=Path.Combine(basePath,@"npm\node_modules\@openai\codex\node_modules\@openai\codex-win32-x64\vendor\x86_64-pc-windows-msvc\bin\codex.exe");if(File.Exists(exe))return exe;exe=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),@".local\bin\codex.exe");return File.Exists(exe)?exe:null;}
 void Finish(){lock(gate){if(job!=IntPtr.Zero){CloseHandle(job);job=IntPtr.Zero;}if(running!=null){try{if(!running.HasExited)running.Kill();}catch{}}}}
 public void Dispose(){lock(gate){disposed=true;}Finish();}
 public Task<QuotaSnapshot> ReadAsync(){return Task.Run(()=>Read());}
 QuotaSnapshot Read(){var snapshot=Cached();var exe=Cli();if(exe==null){snapshot.message="未找到官方 Codex CLI";return snapshot;}Process process=null;try{
  lock(gate){if(disposed)return snapshot;if(running!=null){snapshot.message="额度正在刷新";return snapshot;}}
  using(var replies=new AutoResetEvent(false)){string init=null,quota=null;var responseLock=new object();process=new Process();process.StartInfo=new ProcessStartInfo(exe,"app-server --stdio"){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=System.Text.Encoding.UTF8};process.OutputDataReceived+=(s,e)=>{if(e.Data==null)return;try{var value=Map(json.DeserializeObject(e.Data));double id;if(!Number(Value(value,"id"),out id))return;lock(responseLock){if(id==1)init=e.Data;if(id==2)quota=e.Data;}try{replies.Set();}catch(ObjectDisposedException){}}catch{}};process.ErrorDataReceived+=(s,e)=>{};
   lock(gate){if(disposed)return snapshot;if(!process.Start())throw new IOException();running=process;job=CreateJobObject(IntPtr.Zero,null);var limit=new EXTENDED_LIMIT();limit.basic.flags=0x2000;if(job==IntPtr.Zero||!SetInformationJobObject(job,9,ref limit,(uint)Marshal.SizeOf(typeof(EXTENDED_LIMIT)))||!AssignProcessToJobObject(job,process.Handle))throw new IOException("Cannot contain quota reader process");}
   process.BeginOutputReadLine();process.BeginErrorReadLine();var clock=Stopwatch.StartNew();process.StandardInput.WriteLine("{\"id\":1,\"method\":\"initialize\",\"params\":{\"clientInfo\":{\"name\":\"prism-quota-readonly\",\"version\":\"1.0\"},\"capabilities\":{\"experimentalApi\":true}}}");process.StandardInput.Flush();
   while(clock.ElapsedMilliseconds<10000){lock(gate){if(disposed)return snapshot;}lock(responseLock){if(init!=null)break;}if(process.HasExited)break;replies.WaitOne(100);}
   if(init==null||Value(Map(json.DeserializeObject(init)),"result")==null)throw new IOException();process.StandardInput.WriteLine("{\"method\":\"initialized\",\"params\":{}}");process.StandardInput.WriteLine("{\"id\":2,\"method\":\"account/rateLimits/read\",\"params\":{}}");process.StandardInput.Flush();
   while(clock.ElapsedMilliseconds<10000){lock(gate){if(disposed)return snapshot;}lock(responseLock){if(quota!=null)break;}if(process.HasExited)break;replies.WaitOne(100);}
   if(quota==null||Value(Map(json.DeserializeObject(quota)),"result")==null)throw new IOException();snapshot=Parse(quota,Now());
   if(snapshot.weekly!=null||snapshot.shortTerm!=null){var temp=cache+".tmp";File.WriteAllText(temp,json.Serialize(new{fetchedAt=snapshot.fetchedAt,weekly=snapshot.weekly,shortTerm=snapshot.shortTerm}));if(File.Exists(cache))File.Replace(temp,cache,null);else File.Move(temp,cache);}
   process.StandardInput.Close();return snapshot;
  }
 }catch{snapshot.state=snapshot.fetchedAt>0?"stale":"unknown";snapshot.message=snapshot.fetchedAt>0?"刷新失败，下方为上次记录":"暂时无法读取，请确认 Codex 已登录";return snapshot;}finally{Finish();lock(gate){if(running==process)running=null;}if(process!=null){try{process.WaitForExit(400);}catch{}process.Dispose();}}}
}
