'use strict';
(()=>{
 const $=id=>document.getElementById(id),post=value=>window.chrome?.webview?.postMessage(typeof value==='string'?value:JSON.stringify(value));
 let layout=null,receiveGlass=null,opened=false,amount=0,target=0,raf=0,last=0,filterTimer=0,path='',busy=false,mode='desktop';const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const folder='<svg viewBox="0 0 24 24"><path d="M3 7V5h6l2 2h10v13H3Z"/></svg>',file='<svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6Z M14 3v5h4"/></svg>';
 const titles={quota:'Codex 额度',desktop:'桌面入口',notes:'随手记',tasks:'今日事项',countdown:'倒计时',links:'常用链接',calculator:'计算工具',manage:'管理入口',files:'文件空间'};let visibleCards=['quota','desktop','notes','tasks','countdown','links','calculator'];
 const summaries={desktop:'应用 / 文件',notes:'灵感随记',tasks:'',countdown:'',links:'',calculator:'四则运算'};
 for(const button of document.querySelectorAll('#triggers [data-mode]')){const summary=document.createElement('small');summary.className='rail-summary';summary.textContent=summaries[button.dataset.mode]||'';button.append(summary);const icon=button.querySelector('svg');icon.classList.add('utility-icon');}
 const desktopIcon=document.querySelector('#triggers [data-mode=desktop] svg');desktopIcon.innerHTML='<rect x="2" y="3" width="20" height="16" rx="3"/><path d="M2 8h20M8 8v11M10 22h4"/><circle cx="5" cy="5.5" r=".45" fill="currentColor" stroke="none"/><circle cx="7" cy="5.5" r=".45" fill="currentColor" stroke="none"/><path class="desktop-folders" d="M11 11h3v2h-3zm5 0h3v2h-3zm-5 4h3v2h-3zm5 0h3v2h-3z"/>';
 function summary(name,value){const el=document.querySelector(`#triggers [data-mode="${name}"] .rail-summary`);if(el){el.textContent=value;el.title=value;}}
 function calculate(input){
  if(typeof input!=='string'||input.length>240||/[^0-9.+\-*/()\s×÷]/.test(input))throw Error('只支持数字、括号和四则运算');
  const source=input.replaceAll('×','*').replaceAll('÷','/');let at=0,tokens=0,depth=0;const space=()=>{while(/\s/.test(source[at]||'')&&at<source.length)at++;};
  const bounded=value=>{if(!Number.isFinite(value)||Math.abs(value)>1e100)throw Error('计算结果超出范围');return value;};
  function primary(){space();if(++tokens>160||++depth>20)throw Error('表达式过长或括号层数过多');let result;if(source[at]==='+'||source[at]==='-'){const sign=source[at++];result=primary()*(sign==='-'?-1:1);}else if(source[at]==='('){at++;result=expression();space();if(source[at++]!==')')throw Error('请补齐括号');}else{const match=/^(?:\d+(?:\.\d*)?|\.\d+)/.exec(source.slice(at));if(!match)throw Error('请检查数字和运算符');at+=match[0].length;result=Number(match[0]);}depth--;return bounded(result);}
  function product(){let value=primary();while(true){space();const op=source[at];if(op!=='*'&&op!=='/')return value;at++;const right=primary();if(op==='/'&&right===0)throw Error('不能除以零');value=bounded(op==='*'?value*right:value/right);}}
  function expression(){let value=product();while(true){space();const op=source[at];if(op!=='+'&&op!=='-')return value;at++;const right=product();value=bounded(op==='+'?value+right:value-right);}}
  if(!source.trim())throw Error('先输入一个算式');const result=expression();space();if(at!==source.length)throw Error('请检查数字和运算符');return Number(result.toPrecision(12));
 }
 window.ShelfCalculator={calculate};
 function arrange(hidden=[]){visibleCards=Object.keys(titles).filter(name=>!['manage','files'].includes(name)&&!hidden.includes(name));const top=(620-(visibleCards.length*74+36))/2;document.querySelectorAll('#triggers [data-mode]').forEach(el=>{const index=visibleCards.indexOf(el.dataset.mode);el.hidden=index<0;if(index>=0)el.style.top=top+index*74+'px';});$('manage-trigger').style.top=top+visibleCards.length*74+'px';wake();}
 PrismGlassRenderer($('glass'),message=>{if(message==='painted'||message.startsWith('error:'))post(message);},cb=>receiveGlass=cb);
 function glass(rebuild=false){if(!layout||!receiveGlass)return;const s=layout.scale,top=(620-(visibleCards.length*74+36))/2,cards=[{name:'ShelfRail',x:417*s,y:(top-22)*s,w:82*s,h:(visibleCards.length*74+58)*s,r:26*s,fixedShape:true,rimStrength:.25}];if(amount>.001)cards.push({name:'ShelfPanel',x:(404-400*amount)*s,y:4*s,w:400*amount*s,h:612*s,r:26*s,fixedShape:true,rimStrength:.3});receiveGlass({...layout,type:rebuild?'layout':'geometry',cards});}
 function frame(now){raf=0;const dt=Math.max(.001,Math.min(.05,(now-last)/1000||.016));last=now;amount=layout?.paused||reduced.matches?target:amount+(target-amount)*(1-Math.exp(-16*dt));if(Math.abs(amount-target)<.001)amount=target;const panel=$('panel');panel.style.opacity=String(amount);panel.style.clipPath=`inset(0 0 0 ${(1-amount)*100}% round 26px)`;panel.style.pointerEvents=opened?'auto':'none';post({action:'shape',amount});glass();if(amount!==target)raf=requestAnimationFrame(frame);}
 function wake(){if(!raf){last=performance.now();raf=requestAnimationFrame(frame);}}
 function page(next){mode=next;for(const el of document.querySelectorAll('.page'))el.hidden=el.id!==next+'-page';$('title').textContent=titles[next];$('message').textContent='';document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-expanded',String(opened&&el.dataset.mode===(next==='files'?'desktop':next))));}
 function setExpanded(value,next){opened=value;target=value?1:0;$('panel').inert=!value;$('panel').setAttribute('aria-hidden',String(!value));if(next)page(next);if(!value){pinned=false;clearTimeout(hoverTimer);clearTimeout(closeTimer);clearTimeout(filterTimer);$('filter').value='';document.activeElement?.blur();}wake();}
 function action(name,value){post({action:name,value});}
 let pinned=false,hoverTimer=0,closeTimer=0;
 const cancelClose=()=>clearTimeout(closeTimer),closeLater=()=>{clearTimeout(hoverTimer);clearTimeout(closeTimer);if(!pinned)closeTimer=setTimeout(()=>{if(!pinned)action('close');},250);};
 document.querySelectorAll('[data-mode]').forEach(el=>{el.onclick=()=>{clearTimeout(hoverTimer);cancelClose();const next=el.dataset.mode;if(opened&&mode===next&&pinned){pinned=false;action('close');}else{pinned=true;action('pin-mode',next);}};el.addEventListener('pointerenter',()=>{clearTimeout(hoverTimer);cancelClose();if(!pinned&&(!opened||mode!==el.dataset.mode))hoverTimer=setTimeout(()=>{if(!pinned)action('hover-mode',el.dataset.mode);},210);});el.addEventListener('pointerleave',closeLater);});
 $('panel').addEventListener('pointerenter',()=>{clearTimeout(hoverTimer);cancelClose();});$('panel').addEventListener('pointerleave',closeLater);$('panel').addEventListener('pointerdown',()=>{clearTimeout(hoverTimer);cancelClose();pinned=true;});document.querySelectorAll('[data-system]').forEach(el=>el.onclick=()=>action('system',el.dataset.system));$('close').onclick=()=>action('close');$('browse').onclick=()=>{page('files');action('home');};for(const id of ['back','up','home','pick','more','explorer','copy'])$(id).onclick=()=>{if(['back','up','home','pick'].includes(id)){$('filter').value='';clearTimeout(filterTimer);}action(id);};
 $('quota-refresh').onclick=()=>action('quota-refresh');
 $('note-save').onclick=()=>action('note-save',$('note-text').value);$('note-text').oninput=()=>{$('message').textContent='有未保存的修改';summary('notes','未保存');};$('task-form').onsubmit=e=>{e.preventDefault();const value=$('task-input').value.trim();if(value){action('task-add',value);$('task-input').value='';}};$('countdown-form').onsubmit=e=>{e.preventDefault();post({action:'countdown-save',value:$('countdown-title').value,date:$('countdown-date').value});};
 $('link-form').onsubmit=e=>{e.preventDefault();post({action:'link-add',value:$('link-name').value,url:$('link-url').value});};$('link-restore').onclick=()=>action('link-restore');
 $('calculator-form').onsubmit=e=>{e.preventDefault();try{const result=String(calculate($('calculator-input').value));$('calculator-result').textContent=result;summary('calculator','= '+result);$('calculator-result').classList.remove('invalid');}catch(error){$('calculator-result').textContent=error.message;$('calculator-result').classList.add('invalid');}};
 document.querySelectorAll('[data-key]').forEach(button=>button.onclick=()=>{const input=$('calculator-input'),key=button.dataset.key;if(key==='clear'){input.value='';$('calculator-result').textContent='0';summary('calculator','四则运算');$('calculator-result').classList.remove('invalid');}else if(key==='back'){const start=input.selectionStart,end=input.selectionEnd;input.setRangeText('',start===end?Math.max(0,start-1):start,end,'end');}else if(input.value.length<240)input.setRangeText(key,input.selectionStart,input.selectionEnd,'end');input.focus();});
 $('filter').addEventListener('input',()=>{clearTimeout(filterTimer);filterTimer=setTimeout(()=>action('filter',$('filter').value),240);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')action('close');});
 document.addEventListener('pointermove',e=>receiveGlass?.({type:'pointer',x:e.clientX,y:e.clientY,down:e.buttons===1}));document.addEventListener('pointerleave',()=>receiveGlass?.({type:'pointer',x:-999,y:-999,down:false}));document.addEventListener('pointerdown',e=>receiveGlass?.({type:'pointer',x:e.clientX,y:e.clientY,down:true}));document.addEventListener('pointerup',e=>receiveGlass?.({type:'pointer',x:e.clientX,y:e.clientY,down:false}));
 function size(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(0)+' KB':n<1073741824?(n/1048576).toFixed(1)+' MB':(n/1073741824).toFixed(1)+' GB';}
 function quota(snapshot,busy){const now=Date.now()/1000,fresh=snapshot.state==='fresh'&&snapshot.fetchedAt>0&&now>=snapshot.fetchedAt-30&&now-snapshot.fetchedAt<=600,week=snapshot.weekly,short=snapshot.shortTerm,known=fresh&&week&&Number.isFinite(week.remainingPercent),remaining=known?Math.max(0,Math.min(100,week.remainingPercent)):null,number=remaining===null?'—':String(Math.round(remaining));$('quota-remaining').textContent=remaining===null?'—':number+'%';document.querySelector('.quota-progress').style.strokeDasharray=remaining===null?'0 100':remaining+' 100';document.querySelector('[data-mode=quota]').setAttribute('aria-label',remaining===null?'Codex 周额度未知':'Codex 本周剩余 '+number+'%');document.querySelector('[data-mode=quota]').classList.toggle('quota-unknown',remaining===null);const percent=w=>w&&Number.isFinite(w.remainingPercent)?Math.round(Math.max(0,Math.min(100,w.remainingPercent)))+'%':'未提供';const reset=w=>w?.resetsAt>0?new Date(w.resetsAt*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未提供';$('quota-week-value').textContent=week?(fresh?'':'上次 ')+percent(week):'—';$('quota-week-reset').textContent=reset(week);$('quota-short-value').textContent=short?(fresh?'':'上次 ')+percent(short):'未提供';$('quota-short-label').textContent=short?(short.windowDurationMins%60===0?short.windowDurationMins/60+' 小时剩余':short.windowDurationMins+' 分钟剩余'):'短期额度';$('quota-short-reset').textContent=reset(short);$('quota-status').textContent=busy?'正在刷新…':fresh?snapshot.message||'已读取':snapshot.fetchedAt>0?'额度已过期，显示上次记录':snapshot.message||'尚未读取额度';$('quota-updated').textContent=snapshot.fetchedAt>0?'上次读取：'+new Date(snapshot.fetchedAt*1000).toLocaleString('zh-CN'):'等待读取';$('quota-refresh').disabled=!!busy;}
 function utilities(state){
  const pending=(state.tasks||[]).filter(task=>!task.done).length;summary('tasks',pending?pending+' 项待办':'暂无待办');summary('links',state.links?.length?state.links.length+' 个网址':'未添加');
  if(state.countdownDate){const parts=state.countdownDate.split('-').map(Number),now=new Date(),days=Math.round((Date.UTC(parts[0],parts[1]-1,parts[2])-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);summary('countdown',Number.isFinite(days)?days>0?days+' 天后':days<0?Math.abs(days)+' 天前':'就是今天':'设置日期');}else summary('countdown','设置日期');
  const hidden=state.hiddenCards||[];arrange(hidden);$('manage-list').replaceChildren();const heading=text=>{const label=document.createElement('h3');label.className='manage-heading';label.textContent=text;$('manage-list').append(label);};heading('右侧 · 桌面空间');for(const name of Object.keys(titles).filter(key=>!['manage','files'].includes(key))){const button=document.createElement('button');button.className='manage-row';button.setAttribute('aria-pressed',String(!hidden.includes(name)));const label=document.createElement('span');label.textContent=titles[name];button.append(label,document.createElement('i'));button.onclick=()=>action('card-toggle',name);$('manage-list').append(button);}heading('左侧 · 桌面组件');const leftTitles={network:'网络与电池',Weather:'天气',Music:'音乐',Focus:'专注',Folders:'常用位置',System:'性能',Tools:'工具',Life:'生活'};for(const [name,title] of Object.entries(leftTitles)){const button=document.createElement('button');button.className='manage-row';button.setAttribute('aria-pressed',String(!(state.hiddenLeftCards||[]).includes(name)));const label=document.createElement('span');label.textContent=title;button.append(label,document.createElement('i'));button.onclick=()=>action('left-card-toggle',name);$('manage-list').append(button);}
  $('links-list').replaceChildren();for(const link of state.links||[]){const row=document.createElement('div');row.className='link-row';const open=document.createElement('button');open.className='link-open';const label=document.createElement('span'),url=document.createElement('small');label.textContent=link.name;url.textContent=link.url;open.append(label,url);open.title=link.url;open.onclick=()=>action('link-open',link.id);const remove=document.createElement('button');remove.className='link-remove';remove.textContent='×';remove.setAttribute('aria-label','移除 '+link.name);remove.onclick=()=>action('link-remove',link.id);row.append(open,remove);$('links-list').append(row);}$('links-empty').hidden=!!state.links?.length;$('link-restore').hidden=!state.removedLink;$('link-restore').textContent=state.removedLink?'恢复：'+state.removedLink.name:'恢复最近移除的链接';
 }
 window.chrome?.webview?.addEventListener('message',event=>{const m=event.data;
  if(m.type==='layout'){const previous=layout;layout=m;document.body.dataset.theme=m.theme;document.documentElement.style.setProperty('--scale',m.scale);glass(true);if(!previous||previous.wallpaper!==m.wallpaper)receiveGlass?.({type:'wallpaper',version:m.wallpaper});wake();}
  else if(m.type==='expanded')setExpanded(m.value,m.mode);
  else if(m.type==='quota')quota(m.snapshot,m.busy);
  else if(m.type==='loading'){busy=true;$('status').textContent='正在读取…';$('more').disabled=true;}
  else if(m.type==='error'||m.type==='saved'){$('message').textContent=m.message;if(m.type==='saved')summary('notes','已保存');}
  else if(m.type==='notes'){$('note-text').value=m.text;summary('notes',m.text.trim()?'已记录':'空白便笺');}
  else if(m.type==='local-state'){const s=m.state;utilities(s);$('tasks-list').replaceChildren();for(const task of s.tasks){const button=document.createElement('button');button.className='task'+(task.done?' done':'');button.innerHTML='<i></i><span></span>';button.querySelector('span').textContent=task.text;button.setAttribute('aria-label',(task.done?'标记未完成：':'完成：')+task.text);button.onclick=()=>action('task-toggle',task.id);$('tasks-list').append(button);}$('tasks-empty').hidden=s.tasks.length>0;$('countdown-title').value=s.countdownTitle;$('countdown-date').value=s.countdownDate;if(s.countdownDate){const today=new Date(),parts=s.countdownDate.split('-').map(Number);const targetDate=Date.UTC(parts[0],parts[1]-1,parts[2]),todayDate=Date.UTC(today.getFullYear(),today.getMonth(),today.getDate()),days=Math.round((targetDate-todayDate)/86400000);$('countdown-name').textContent=s.countdownTitle;$('countdown-days').textContent=Math.abs(days);$('countdown-label').textContent=days>0?'天后到来':days<0?'天前已到来':'就是今天';}}
  else if(m.type==='desktop'){busy=false;summary('desktop',m.entries.length+(m.truncated?'+':'')+' 项');$('desktop-grid').replaceChildren();for(const entry of m.entries){const button=document.createElement('button');button.className='desktop-entry';button.dataset.path=entry.path;if(entry.icon){const img=document.createElement('img');img.src=entry.icon;img.alt='';button.append(img);}else button.innerHTML=entry.directory?folder:file;const label=document.createElement('span');label.textContent=entry.name;button.append(label);button.title=entry.name;button.onclick=()=>{if(!busy)action('open',entry.path);};$('desktop-grid').append(button);}if(!m.entries.length)$('message').textContent='桌面还没有可显示的文件。';else if(m.truncated)$('message').textContent='已显示前 1000 项，其余请通过浏览文件打开桌面。';}
  else if(m.type==='icon'){const button=[...document.querySelectorAll('.desktop-entry')].find(el=>el.dataset.path===m.path);if(button){const img=document.createElement('img');img.src=m.icon;img.alt='';button.firstElementChild.replaceWith(img);}}
  else if(m.type==='page'){
   busy=false;$('more').disabled=false;page('files');if(m.error){$('status').textContent=m.error;return;}path=m.path;$('path').textContent=path||'此电脑 · 常用位置与驱动器';$('path').title=path||'此电脑';$('filter').disabled=!path;$('copy').disabled=!path;$('up').disabled=!path;$('back').disabled=!m.canBack;
   if(!m.append)$('list').replaceChildren();for(const entry of m.entries){const button=document.createElement('button');button.className='entry';button.innerHTML=(entry.directory?folder:file)+'<span><b></b><small></small></span><em></em>';button.querySelector('b').textContent=entry.name;button.querySelector('small').textContent=entry.directory?'文件夹':size(entry.size)+' · '+entry.modified;button.querySelector('em').textContent=entry.directory?'›':'↗';button.title=entry.path;button.onclick=()=>{if(!busy){clearTimeout(filterTimer);if(entry.directory)$('filter').value='';action('open',entry.path);}};$('list').append(button);}
   $('more').hidden=!m.more;$('more').textContent=m.entries.length?'继续加载':'继续查找此文件夹';$('status').textContent=$('list').children.length?'':m.more?'当前批次没有匹配，继续加载可浏览后续文件。':'没有可显示的文件。';
   $('hint').textContent=path?'仅按名称筛选当前文件夹 · 不含子文件夹':'按需浏览文件夹，不进行全盘索引';
  }
 });arrange();post('ready');
})();
